//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/8/2013 6:37:09 PM
namespace Sujut.SujutApi
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Sujut.Models.Api", "Sujut.SujutApi.Sujut.Models.Api");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sujut.Core", "Sujut.SujutApi");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Sujut.SujutApi.Sujut.Models.Api", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Sujut.Models.Api.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sujut.SujutApi", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Sujut.Core.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for DebtCalculations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DebtCalculation> DebtCalculations
        {
            get
            {
                if ((this._DebtCalculations == null))
                {
                    this._DebtCalculations = base.CreateQuery<DebtCalculation>("DebtCalculations");
                }
                return this._DebtCalculations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DebtCalculation> _DebtCalculations;
        /// <summary>
        /// There are no comments for Participants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Participant> Participants
        {
            get
            {
                if ((this._Participants == null))
                {
                    this._Participants = base.CreateQuery<Participant>("Participants");
                }
                return this._Participants;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Participant> _Participants;
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Expense> Expenses
        {
            get
            {
                if ((this._Expenses == null))
                {
                    this._Expenses = base.CreateQuery<Expense>("Expenses");
                }
                return this._Expenses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Expense> _Expenses;
        /// <summary>
        /// There are no comments for Debts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Debt> Debts
        {
            get
            {
                if ((this._Debts == null))
                {
                    this._Debts = base.CreateQuery<Debt>("Debts");
                }
                return this._Debts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Debt> _Debts;
        /// <summary>
        /// There are no comments for Debtors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Debtor> Debtors
        {
            get
            {
                if ((this._Debtors == null))
                {
                    this._Debtors = base.CreateQuery<Debtor>("Debtors");
                }
                return this._Debtors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Debtor> _Debtors;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for DebtCalculations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDebtCalculations(DebtCalculation debtCalculation)
        {
            base.AddObject("DebtCalculations", debtCalculation);
        }
        /// <summary>
        /// There are no comments for Participants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToParticipants(Participant participant)
        {
            base.AddObject("Participants", participant);
        }
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToExpenses(Expense expense)
        {
            base.AddObject("Expenses", expense);
        }
        /// <summary>
        /// There are no comments for Debts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDebts(Debt debt)
        {
            base.AddObject("Debts", debt);
        }
        /// <summary>
        /// There are no comments for Debtors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDebtors(Debtor debtor)
        {
            base.AddObject("Debtors", debtor);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Sujut.Core\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Ent" +
                "ityType Name=\"DebtCalculation\"><Key><PropertyRef Name=\"Id\" /></Key><Property Nam" +
                "e=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.Strin" +
                "g\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Currency\" " +
                "Type=\"Edm.String\" /><Property Name=\"LastActivityTime\" Type=\"Edm.DateTime\" Nullab" +
                "le=\"false\" /><Property Name=\"Phase\" Type=\"Edm.String\" Nullable=\"false\" /><Naviga" +
                "tionProperty Name=\"Creator\" Relationship=\"Sujut.Core.Sujut_Core_DebtCalculation_" +
                "Creator_Sujut_Core_User_CreatorPartner\" ToRole=\"Creator\" FromRole=\"CreatorPartne" +
                "r\" /><NavigationProperty Name=\"Participants\" Relationship=\"Sujut.Core.Sujut_Core" +
                "_DebtCalculation_Participants_Sujut_Core_Participant_ParticipantsPartner\" ToRole" +
                "=\"Participants\" FromRole=\"ParticipantsPartner\" /><NavigationProperty Name=\"Expen" +
                "ses\" Relationship=\"Sujut.Core.Sujut_Core_DebtCalculation_Expenses_Sujut_Core_Exp" +
                "ense_ExpensesPartner\" ToRole=\"Expenses\" FromRole=\"ExpensesPartner\" /><Navigation" +
                "Property Name=\"Debts\" Relationship=\"Sujut.Core.Sujut_Core_DebtCalculation_Debts_" +
                "Sujut_Core_Debt_DebtsPartner\" ToRole=\"Debts\" FromRole=\"DebtsPartner\" /></EntityT" +
                "ype><EntityType Name=\"Participant\"><Key><PropertyRef Name=\"Id\" /></Key><Property" +
                " Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"CanEdit\" Type=\"Ed" +
                "m.Boolean\" Nullable=\"false\" /><Property Name=\"DoneAddingExpenses\" Type=\"Edm.Bool" +
                "ean\" Nullable=\"false\" /><Property Name=\"LastExpenseReminderEmailSent\" Type=\"Edm." +
                "DateTime\" /><Property Name=\"HasPaid\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Prop" +
                "erty Name=\"LastPaymentReminderEmailSent\" Type=\"Edm.DateTime\" /><NavigationProper" +
                "ty Name=\"User\" Relationship=\"Sujut.Core.Sujut_Core_Participant_User_Sujut_Core_U" +
                "ser_UserPartner\" ToRole=\"User\" FromRole=\"UserPartner\" /><NavigationProperty Name" +
                "=\"DebtCalculation\" Relationship=\"Sujut.Core.Sujut_Core_Participant_DebtCalculati" +
                "on_Sujut_Core_DebtCalculation_DebtCalculationPartner\" ToRole=\"DebtCalculation\" F" +
                "romRole=\"DebtCalculationPartner\" /></EntityType><EntityType Name=\"Expense\"><Key>" +
                "<PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"fa" +
                "lse\" /><Property Name=\"Amount\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property N" +
                "ame=\"Description\" Type=\"Edm.String\" /><Property Name=\"AddedTime\" Type=\"Edm.DateT" +
                "ime\" Nullable=\"false\" /><NavigationProperty Name=\"DebtCalculation\" Relationship=" +
                "\"Sujut.Core.Sujut_Core_Expense_DebtCalculation_Sujut_Core_DebtCalculation_DebtCa" +
                "lculationPartner\" ToRole=\"DebtCalculation\" FromRole=\"DebtCalculationPartner\" /><" +
                "NavigationProperty Name=\"Payer\" Relationship=\"Sujut.Core.Sujut_Core_Expense_Paye" +
                "r_Sujut_Core_User_PayerPartner\" ToRole=\"Payer\" FromRole=\"PayerPartner\" /><Naviga" +
                "tionProperty Name=\"Debtors\" Relationship=\"Sujut.Core.Sujut_Core_Expense_Debtors_" +
                "Sujut_Core_Debtor_DebtorsPartner\" ToRole=\"Debtors\" FromRole=\"DebtorsPartner\" /><" +
                "/EntityType><EntityType Name=\"Debt\"><Key><PropertyRef Name=\"Id\" /></Key><Propert" +
                "y Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Amount\" Type=\"Ed" +
                "m.Decimal\" Nullable=\"false\" /><NavigationProperty Name=\"DebtCalculation\" Relatio" +
                "nship=\"Sujut.Core.Sujut_Core_Debt_DebtCalculation_Sujut_Core_DebtCalculation_Deb" +
                "tCalculationPartner\" ToRole=\"DebtCalculation\" FromRole=\"DebtCalculationPartner\" " +
                "/><NavigationProperty Name=\"Debtor\" Relationship=\"Sujut.Core.Sujut_Core_Debt_Deb" +
                "tor_Sujut_Core_User_DebtorPartner\" ToRole=\"Debtor\" FromRole=\"DebtorPartner\" /><N" +
                "avigationProperty Name=\"Creditor\" Relationship=\"Sujut.Core.Sujut_Core_Debt_Credi" +
                "tor_Sujut_Core_User_CreditorPartner\" ToRole=\"Creditor\" FromRole=\"CreditorPartner" +
                "\" /></EntityType><EntityType Name=\"Debtor\"><Key><PropertyRef Name=\"Id\" /></Key><" +
                "Property Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" /><NavigationProperty Name=" +
                "\"User\" Relationship=\"Sujut.Core.Sujut_Core_Debtor_User_Sujut_Core_User_UserPartn" +
                "er\" ToRole=\"User\" FromRole=\"UserPartner\" /><NavigationProperty Name=\"Expense\" Re" +
                "lationship=\"Sujut.Core.Sujut_Core_Debtor_Expense_Sujut_Core_Expense_ExpensePartn" +
                "er\" ToRole=\"Expense\" FromRole=\"ExpensePartner\" /></EntityType><EntityType Name=\"" +
                "User\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int64\" N" +
                "ullable=\"false\" /><Property Name=\"Firstname\" Type=\"Edm.String\" /><Property Name=" +
                "\"Lastname\" Type=\"Edm.String\" /><Property Name=\"AllowSearchByName\" Type=\"Edm.Bool" +
                "ean\" Nullable=\"false\" /><Property Name=\"PaymentInstructions\" Type=\"Edm.String\" /" +
                "><Property Name=\"TimeZone\" Type=\"Edm.String\" /><Property Name=\"Language\" Type=\"E" +
                "dm.String\" /><Property Name=\"Culture\" Type=\"Edm.String\" /><NavigationProperty Na" +
                "me=\"Participations\" Relationship=\"Sujut.Core.Sujut_Core_User_Participations_Suju" +
                "t_Core_Participant_ParticipationsPartner\" ToRole=\"Participations\" FromRole=\"Part" +
                "icipationsPartner\" /></EntityType><Association Name=\"Sujut_Core_DebtCalculation_" +
                "Creator_Sujut_Core_User_CreatorPartner\"><End Type=\"Sujut.Core.User\" Role=\"Creato" +
                "r\" Multiplicity=\"0..1\" /><End Type=\"Sujut.Core.DebtCalculation\" Role=\"CreatorPar" +
                "tner\" Multiplicity=\"0..1\" /></Association><Association Name=\"Sujut_Core_DebtCalc" +
                "ulation_Participants_Sujut_Core_Participant_ParticipantsPartner\"><End Type=\"Suju" +
                "t.Core.Participant\" Role=\"Participants\" Multiplicity=\"*\" /><End Type=\"Sujut.Core" +
                ".DebtCalculation\" Role=\"ParticipantsPartner\" Multiplicity=\"0..1\" /></Association" +
                "><Association Name=\"Sujut_Core_DebtCalculation_Expenses_Sujut_Core_Expense_Expen" +
                "sesPartner\"><End Type=\"Sujut.Core.Expense\" Role=\"Expenses\" Multiplicity=\"*\" /><E" +
                "nd Type=\"Sujut.Core.DebtCalculation\" Role=\"ExpensesPartner\" Multiplicity=\"0..1\" " +
                "/></Association><Association Name=\"Sujut_Core_DebtCalculation_Debts_Sujut_Core_D" +
                "ebt_DebtsPartner\"><End Type=\"Sujut.Core.Debt\" Role=\"Debts\" Multiplicity=\"*\" /><E" +
                "nd Type=\"Sujut.Core.DebtCalculation\" Role=\"DebtsPartner\" Multiplicity=\"0..1\" /><" +
                "/Association><Association Name=\"Sujut_Core_Participant_User_Sujut_Core_User_User" +
                "Partner\"><End Type=\"Sujut.Core.User\" Role=\"User\" Multiplicity=\"0..1\" /><End Type" +
                "=\"Sujut.Core.Participant\" Role=\"UserPartner\" Multiplicity=\"0..1\" /></Association" +
                "><Association Name=\"Sujut_Core_Participant_DebtCalculation_Sujut_Core_DebtCalcul" +
                "ation_DebtCalculationPartner\"><End Type=\"Sujut.Core.DebtCalculation\" Role=\"DebtC" +
                "alculation\" Multiplicity=\"0..1\" /><End Type=\"Sujut.Core.Participant\" Role=\"DebtC" +
                "alculationPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"Sujut_" +
                "Core_Expense_DebtCalculation_Sujut_Core_DebtCalculation_DebtCalculationPartner\">" +
                "<End Type=\"Sujut.Core.DebtCalculation\" Role=\"DebtCalculation\" Multiplicity=\"0..1" +
                "\" /><End Type=\"Sujut.Core.Expense\" Role=\"DebtCalculationPartner\" Multiplicity=\"0" +
                "..1\" /></Association><Association Name=\"Sujut_Core_Expense_Payer_Sujut_Core_User" +
                "_PayerPartner\"><End Type=\"Sujut.Core.User\" Role=\"Payer\" Multiplicity=\"0..1\" /><E" +
                "nd Type=\"Sujut.Core.Expense\" Role=\"PayerPartner\" Multiplicity=\"0..1\" /></Associa" +
                "tion><Association Name=\"Sujut_Core_Expense_Debtors_Sujut_Core_Debtor_DebtorsPart" +
                "ner\"><End Type=\"Sujut.Core.Debtor\" Role=\"Debtors\" Multiplicity=\"*\" /><End Type=\"" +
                "Sujut.Core.Expense\" Role=\"DebtorsPartner\" Multiplicity=\"0..1\" /></Association><A" +
                "ssociation Name=\"Sujut_Core_Debt_DebtCalculation_Sujut_Core_DebtCalculation_Debt" +
                "CalculationPartner\"><End Type=\"Sujut.Core.DebtCalculation\" Role=\"DebtCalculation" +
                "\" Multiplicity=\"0..1\" /><End Type=\"Sujut.Core.Debt\" Role=\"D";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "ebtCalculationPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"Suj" +
                "ut_Core_Debt_Debtor_Sujut_Core_User_DebtorPartner\"><End Type=\"Sujut.Core.User\" R" +
                "ole=\"Debtor\" Multiplicity=\"0..1\" /><End Type=\"Sujut.Core.Debt\" Role=\"DebtorPartn" +
                "er\" Multiplicity=\"0..1\" /></Association><Association Name=\"Sujut_Core_Debt_Credi" +
                "tor_Sujut_Core_User_CreditorPartner\"><End Type=\"Sujut.Core.User\" Role=\"Creditor\"" +
                " Multiplicity=\"0..1\" /><End Type=\"Sujut.Core.Debt\" Role=\"CreditorPartner\" Multip" +
                "licity=\"0..1\" /></Association><Association Name=\"Sujut_Core_Debtor_User_Sujut_Co" +
                "re_User_UserPartner\"><End Type=\"Sujut.Core.User\" Role=\"User\" Multiplicity=\"0..1\"" +
                " /><End Type=\"Sujut.Core.Debtor\" Role=\"UserPartner\" Multiplicity=\"0..1\" /></Asso" +
                "ciation><Association Name=\"Sujut_Core_Debtor_Expense_Sujut_Core_Expense_ExpenseP" +
                "artner\"><End Type=\"Sujut.Core.Expense\" Role=\"Expense\" Multiplicity=\"0..1\" /><End" +
                " Type=\"Sujut.Core.Debtor\" Role=\"ExpensePartner\" Multiplicity=\"0..1\" /></Associat" +
                "ion><Association Name=\"Sujut_Core_User_Participations_Sujut_Core_Participant_Par" +
                "ticipationsPartner\"><End Type=\"Sujut.Core.Participant\" Role=\"Participations\" Mul" +
                "tiplicity=\"*\" /><End Type=\"Sujut.Core.User\" Role=\"ParticipationsPartner\" Multipl" +
                "icity=\"0..1\" /></Association></Schema><Schema Namespace=\"Sujut.Models.Api\" xmlns" +
                "=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityType Name=\"ExpenseApiMode" +
                "l\" BaseType=\"Sujut.Core.Expense\"><Property Name=\"PayerId\" Type=\"Edm.Int64\" Nulla" +
                "ble=\"false\" /><Property Name=\"DebtorIds\" Type=\"Collection(Edm.Int64)\" Nullable=\"" +
                "false\" /></EntityType></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas" +
                ".microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEnt" +
                "ityContainer=\"true\"><EntitySet Name=\"DebtCalculations\" EntityType=\"Sujut.Core.De" +
                "btCalculation\" /><EntitySet Name=\"Participants\" EntityType=\"Sujut.Core.Participa" +
                "nt\" /><EntitySet Name=\"Expenses\" EntityType=\"Sujut.Core.Expense\" /><EntitySet Na" +
                "me=\"Debts\" EntityType=\"Sujut.Core.Debt\" /><EntitySet Name=\"Debtors\" EntityType=\"" +
                "Sujut.Core.Debtor\" /><EntitySet Name=\"Users\" EntityType=\"Sujut.Core.User\" /><Fun" +
                "ctionImport Name=\"AddExistingUser\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><" +
                "Parameter Name=\"bindingParameter\" Type=\"Sujut.Core.DebtCalculation\" /><Parameter" +
                " Name=\"UserId\" Type=\"Edm.Int64\" Nullable=\"false\" /></FunctionImport><FunctionImp" +
                "ort Name=\"AddNewUser\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Nam" +
                "e=\"bindingParameter\" Type=\"Sujut.Core.DebtCalculation\" /><Parameter Name=\"Email\"" +
                " Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><Parameter Name=\"Firstn" +
                "ame\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><Parameter Name=\"La" +
                "stname\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /></FunctionImport" +
                "><FunctionImport Name=\"Start\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><Param" +
                "eter Name=\"bindingParameter\" Type=\"Sujut.Core.DebtCalculation\" /></FunctionImpor" +
                "t><FunctionImport Name=\"DoneAddingExpenses\" IsBindable=\"true\" m:IsAlwaysBindable" +
                "=\"true\"><Parameter Name=\"bindingParameter\" Type=\"Sujut.Core.DebtCalculation\" /><" +
                "/FunctionImport><FunctionImport Name=\"Paid\" IsBindable=\"true\" m:IsAlwaysBindable" +
                "=\"true\"><Parameter Name=\"bindingParameter\" Type=\"Sujut.Core.DebtCalculation\" /><" +
                "/FunctionImport><FunctionImport Name=\"Validate\" ReturnType=\"Edm.Int64\" IsBindabl" +
                "e=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bindingParameter\" Type=\"Coll" +
                "ection(Sujut.Core.User)\" Nullable=\"false\" /><Parameter Name=\"Email\" Type=\"Edm.St" +
                "ring\" FixedLength=\"false\" Unicode=\"false\" /><Parameter Name=\"Password\" Type=\"Edm" +
                ".String\" FixedLength=\"false\" Unicode=\"false\" /></FunctionImport><FunctionImport " +
                "Name=\"Register\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bin" +
                "dingParameter\" Type=\"Collection(Sujut.Core.User)\" Nullable=\"false\" /><Parameter " +
                "Name=\"Email\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><Parameter " +
                "Name=\"Firstname\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><Parame" +
                "ter Name=\"Lastname\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><Par" +
                "ameter Name=\"Password\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><" +
                "Parameter Name=\"Language\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" " +
                "/><Parameter Name=\"Culture\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false" +
                "\" /></FunctionImport><AssociationSet Name=\"Sujut_Core_DebtCalculation_Creator_Su" +
                "jut_Core_User_CreatorPartnerSet\" Association=\"Sujut.Core.Sujut_Core_DebtCalculat" +
                "ion_Creator_Sujut_Core_User_CreatorPartner\"><End Role=\"CreatorPartner\" EntitySet" +
                "=\"DebtCalculations\" /><End Role=\"Creator\" EntitySet=\"Users\" /></AssociationSet><" +
                "AssociationSet Name=\"Sujut_Core_DebtCalculation_Participants_Sujut_Core_Particip" +
                "ant_ParticipantsPartnerSet\" Association=\"Sujut.Core.Sujut_Core_DebtCalculation_P" +
                "articipants_Sujut_Core_Participant_ParticipantsPartner\"><End Role=\"ParticipantsP" +
                "artner\" EntitySet=\"DebtCalculations\" /><End Role=\"Participants\" EntitySet=\"Parti" +
                "cipants\" /></AssociationSet><AssociationSet Name=\"Sujut_Core_DebtCalculation_Exp" +
                "enses_Sujut_Core_Expense_ExpensesPartnerSet\" Association=\"Sujut.Core.Sujut_Core_" +
                "DebtCalculation_Expenses_Sujut_Core_Expense_ExpensesPartner\"><End Role=\"Expenses" +
                "Partner\" EntitySet=\"DebtCalculations\" /><End Role=\"Expenses\" EntitySet=\"Expenses" +
                "\" /></AssociationSet><AssociationSet Name=\"Sujut_Core_DebtCalculation_Debts_Suju" +
                "t_Core_Debt_DebtsPartnerSet\" Association=\"Sujut.Core.Sujut_Core_DebtCalculation_" +
                "Debts_Sujut_Core_Debt_DebtsPartner\"><End Role=\"DebtsPartner\" EntitySet=\"DebtCalc" +
                "ulations\" /><End Role=\"Debts\" EntitySet=\"Debts\" /></AssociationSet><AssociationS" +
                "et Name=\"Sujut_Core_Participant_User_Sujut_Core_User_UserPartnerSet\" Association" +
                "=\"Sujut.Core.Sujut_Core_Participant_User_Sujut_Core_User_UserPartner\"><End Role=" +
                "\"UserPartner\" EntitySet=\"Participants\" /><End Role=\"User\" EntitySet=\"Users\" /></" +
                "AssociationSet><AssociationSet Name=\"Sujut_Core_Participant_DebtCalculation_Suju" +
                "t_Core_DebtCalculation_DebtCalculationPartnerSet\" Association=\"Sujut.Core.Sujut_" +
                "Core_Participant_DebtCalculation_Sujut_Core_DebtCalculation_DebtCalculationPartn" +
                "er\"><End Role=\"DebtCalculationPartner\" EntitySet=\"Participants\" /><End Role=\"Deb" +
                "tCalculation\" EntitySet=\"DebtCalculations\" /></AssociationSet><AssociationSet Na" +
                "me=\"Sujut_Core_Expense_DebtCalculation_Sujut_Core_DebtCalculation_DebtCalculatio" +
                "nPartnerSet\" Association=\"Sujut.Core.Sujut_Core_Expense_DebtCalculation_Sujut_Co" +
                "re_DebtCalculation_DebtCalculationPartner\"><End Role=\"DebtCalculationPartner\" En" +
                "titySet=\"Expenses\" /><End Role=\"DebtCalculation\" EntitySet=\"DebtCalculations\" />" +
                "</AssociationSet><AssociationSet Name=\"Sujut_Core_Expense_Payer_Sujut_Core_User_" +
                "PayerPartnerSet\" Association=\"Sujut.Core.Sujut_Core_Expense_Payer_Sujut_Core_Use" +
                "r_PayerPartner\"><End Role=\"PayerPartner\" EntitySet=\"Expenses\" /><End Role=\"Payer" +
                "\" EntitySet=\"Users\" /></AssociationSet><AssociationSet Name=\"Sujut_Core_Expense_" +
                "Debtors_Sujut_Core_Debtor_DebtorsPartnerSet\" Association=\"Sujut.Core.Sujut_Core_" +
                "Expense_Debtors_Sujut_Core_Debtor_DebtorsPartner\"><End Role=\"DebtorsPartner\" Ent" +
                "itySet=\"Expenses\" /><End Role=\"Debtors\" EntitySet=\"Debtors\" /></AssociationSet><" +
                "AssociationSet Name=\"Sujut_Core_Debt_DebtCalculation_Sujut_Core_DebtCalculation_" +
                "DebtCalculationPartnerSet\" Association=\"Sujut.Core.Sujut_Core_Debt_DebtCalculati" +
                "on_Sujut_Core_DebtCalculation_DebtCalculationPartner\"><End Role=\"DebtCalculation" +
                "Partner\" EntitySet=\"Debts\" /><End Role=\"DebtCalculation\" EntitySet=\"DebtCalculat" +
                "ions\" /></AssociationSet><AssociationSet Name=\"Sujut_Core_Debt_Debtor_Sujut_Core" +
                "_User_DebtorPartnerSet\" Association=\"Sujut.Core.Sujut_Core_";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart2 = @"Debt_Debtor_Sujut_Core_User_DebtorPartner""><End Role=""DebtorPartner"" EntitySet=""Debts"" /><End Role=""Debtor"" EntitySet=""Users"" /></AssociationSet><AssociationSet Name=""Sujut_Core_Debt_Creditor_Sujut_Core_User_CreditorPartnerSet"" Association=""Sujut.Core.Sujut_Core_Debt_Creditor_Sujut_Core_User_CreditorPartner""><End Role=""CreditorPartner"" EntitySet=""Debts"" /><End Role=""Creditor"" EntitySet=""Users"" /></AssociationSet><AssociationSet Name=""Sujut_Core_Debtor_User_Sujut_Core_User_UserPartnerSet"" Association=""Sujut.Core.Sujut_Core_Debtor_User_Sujut_Core_User_UserPartner""><End Role=""UserPartner"" EntitySet=""Debtors"" /><End Role=""User"" EntitySet=""Users"" /></AssociationSet><AssociationSet Name=""Sujut_Core_Debtor_Expense_Sujut_Core_Expense_ExpensePartnerSet"" Association=""Sujut.Core.Sujut_Core_Debtor_Expense_Sujut_Core_Expense_ExpensePartner""><End Role=""ExpensePartner"" EntitySet=""Debtors"" /><End Role=""Expense"" EntitySet=""Expenses"" /></AssociationSet><AssociationSet Name=""Sujut_Core_User_Participations_Sujut_Core_Participant_ParticipationsPartnerSet"" Association=""Sujut.Core.Sujut_Core_User_Participations_Sujut_Core_Participant_ParticipationsPartner""><End Role=""ParticipationsPartner"" EntitySet=""Users"" /><End Role=""Participations"" EntitySet=""Participants"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1, ModelPart2);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sujut.Core.DebtCalculation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DebtCalculations")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DebtCalculation : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DebtCalculation object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="lastActivityTime">Initial value of LastActivityTime.</param>
        /// <param name="phase">Initial value of Phase.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DebtCalculation CreateDebtCalculation(long ID, global::System.DateTime lastActivityTime, string phase)
        {
            DebtCalculation debtCalculation = new DebtCalculation();
            debtCalculation.Id = ID;
            debtCalculation.LastActivityTime = lastActivityTime;
            debtCalculation.Phase = phase;
            return debtCalculation;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Currency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Currency
        {
            get
            {
                return this._Currency;
            }
            set
            {
                this.OnCurrencyChanging(value);
                this._Currency = value;
                this.OnCurrencyChanged();
                this.OnPropertyChanged("Currency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Currency;
        partial void OnCurrencyChanging(string value);
        partial void OnCurrencyChanged();
        /// <summary>
        /// There are no comments for Property LastActivityTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastActivityTime
        {
            get
            {
                return this._LastActivityTime;
            }
            set
            {
                this.OnLastActivityTimeChanging(value);
                this._LastActivityTime = value;
                this.OnLastActivityTimeChanged();
                this.OnPropertyChanged("LastActivityTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastActivityTime;
        partial void OnLastActivityTimeChanging(global::System.DateTime value);
        partial void OnLastActivityTimeChanged();
        /// <summary>
        /// There are no comments for Property Phase in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phase
        {
            get
            {
                return this._Phase;
            }
            set
            {
                this.OnPhaseChanging(value);
                this._Phase = value;
                this.OnPhaseChanged();
                this.OnPropertyChanged("Phase");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phase;
        partial void OnPhaseChanging(string value);
        partial void OnPhaseChanged();
        /// <summary>
        /// There are no comments for Creator in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Creator
        {
            get
            {
                return this._Creator;
            }
            set
            {
                this._Creator = value;
                this.OnPropertyChanged("Creator");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Creator;
        /// <summary>
        /// There are no comments for Participants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Participant> Participants
        {
            get
            {
                return this._Participants;
            }
            set
            {
                this._Participants = value;
                this.OnPropertyChanged("Participants");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Participant> _Participants = new global::System.Data.Services.Client.DataServiceCollection<Participant>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Expense> Expenses
        {
            get
            {
                return this._Expenses;
            }
            set
            {
                this._Expenses = value;
                this.OnPropertyChanged("Expenses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Expense> _Expenses = new global::System.Data.Services.Client.DataServiceCollection<Expense>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Debts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Debt> Debts
        {
            get
            {
                return this._Debts;
            }
            set
            {
                this._Debts = value;
                this.OnPropertyChanged("Debts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Debt> _Debts = new global::System.Data.Services.Client.DataServiceCollection<Debt>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sujut.Core.Participant in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Participants")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Participant : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Participant object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="canEdit">Initial value of CanEdit.</param>
        /// <param name="doneAddingExpenses">Initial value of DoneAddingExpenses.</param>
        /// <param name="hasPaid">Initial value of HasPaid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Participant CreateParticipant(long ID, bool canEdit, bool doneAddingExpenses, bool hasPaid)
        {
            Participant participant = new Participant();
            participant.Id = ID;
            participant.CanEdit = canEdit;
            participant.DoneAddingExpenses = doneAddingExpenses;
            participant.HasPaid = hasPaid;
            return participant;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CanEdit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool CanEdit
        {
            get
            {
                return this._CanEdit;
            }
            set
            {
                this.OnCanEditChanging(value);
                this._CanEdit = value;
                this.OnCanEditChanged();
                this.OnPropertyChanged("CanEdit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _CanEdit;
        partial void OnCanEditChanging(bool value);
        partial void OnCanEditChanged();
        /// <summary>
        /// There are no comments for Property DoneAddingExpenses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool DoneAddingExpenses
        {
            get
            {
                return this._DoneAddingExpenses;
            }
            set
            {
                this.OnDoneAddingExpensesChanging(value);
                this._DoneAddingExpenses = value;
                this.OnDoneAddingExpensesChanged();
                this.OnPropertyChanged("DoneAddingExpenses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _DoneAddingExpenses;
        partial void OnDoneAddingExpensesChanging(bool value);
        partial void OnDoneAddingExpensesChanged();
        /// <summary>
        /// There are no comments for Property LastExpenseReminderEmailSent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastExpenseReminderEmailSent
        {
            get
            {
                return this._LastExpenseReminderEmailSent;
            }
            set
            {
                this.OnLastExpenseReminderEmailSentChanging(value);
                this._LastExpenseReminderEmailSent = value;
                this.OnLastExpenseReminderEmailSentChanged();
                this.OnPropertyChanged("LastExpenseReminderEmailSent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastExpenseReminderEmailSent;
        partial void OnLastExpenseReminderEmailSentChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastExpenseReminderEmailSentChanged();
        /// <summary>
        /// There are no comments for Property HasPaid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool HasPaid
        {
            get
            {
                return this._HasPaid;
            }
            set
            {
                this.OnHasPaidChanging(value);
                this._HasPaid = value;
                this.OnHasPaidChanged();
                this.OnPropertyChanged("HasPaid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _HasPaid;
        partial void OnHasPaidChanging(bool value);
        partial void OnHasPaidChanged();
        /// <summary>
        /// There are no comments for Property LastPaymentReminderEmailSent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastPaymentReminderEmailSent
        {
            get
            {
                return this._LastPaymentReminderEmailSent;
            }
            set
            {
                this.OnLastPaymentReminderEmailSentChanging(value);
                this._LastPaymentReminderEmailSent = value;
                this.OnLastPaymentReminderEmailSentChanged();
                this.OnPropertyChanged("LastPaymentReminderEmailSent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastPaymentReminderEmailSent;
        partial void OnLastPaymentReminderEmailSentChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastPaymentReminderEmailSentChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
        /// <summary>
        /// There are no comments for DebtCalculation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DebtCalculation DebtCalculation
        {
            get
            {
                return this._DebtCalculation;
            }
            set
            {
                this._DebtCalculation = value;
                this.OnPropertyChanged("DebtCalculation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DebtCalculation _DebtCalculation;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sujut.Core.Expense in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Expenses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Expense : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Expense object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="amount">Initial value of Amount.</param>
        /// <param name="addedTime">Initial value of AddedTime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Expense CreateExpense(long ID, decimal amount, global::System.DateTime addedTime)
        {
            Expense expense = new Expense();
            expense.Id = ID;
            expense.Amount = amount;
            expense.AddedTime = addedTime;
            return expense;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
                this.OnPropertyChanged("Amount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Amount;
        partial void OnAmountChanging(decimal value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property AddedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime AddedTime
        {
            get
            {
                return this._AddedTime;
            }
            set
            {
                this.OnAddedTimeChanging(value);
                this._AddedTime = value;
                this.OnAddedTimeChanged();
                this.OnPropertyChanged("AddedTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _AddedTime;
        partial void OnAddedTimeChanging(global::System.DateTime value);
        partial void OnAddedTimeChanged();
        /// <summary>
        /// There are no comments for DebtCalculation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DebtCalculation DebtCalculation
        {
            get
            {
                return this._DebtCalculation;
            }
            set
            {
                this._DebtCalculation = value;
                this.OnPropertyChanged("DebtCalculation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DebtCalculation _DebtCalculation;
        /// <summary>
        /// There are no comments for Payer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Payer
        {
            get
            {
                return this._Payer;
            }
            set
            {
                this._Payer = value;
                this.OnPropertyChanged("Payer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Payer;
        /// <summary>
        /// There are no comments for Debtors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Debtor> Debtors
        {
            get
            {
                return this._Debtors;
            }
            set
            {
                this._Debtors = value;
                this.OnPropertyChanged("Debtors");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Debtor> _Debtors = new global::System.Data.Services.Client.DataServiceCollection<Debtor>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sujut.Core.Debt in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Debts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Debt : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Debt object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="amount">Initial value of Amount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Debt CreateDebt(long ID, decimal amount)
        {
            Debt debt = new Debt();
            debt.Id = ID;
            debt.Amount = amount;
            return debt;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
                this.OnPropertyChanged("Amount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Amount;
        partial void OnAmountChanging(decimal value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for DebtCalculation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DebtCalculation DebtCalculation
        {
            get
            {
                return this._DebtCalculation;
            }
            set
            {
                this._DebtCalculation = value;
                this.OnPropertyChanged("DebtCalculation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DebtCalculation _DebtCalculation;
        /// <summary>
        /// There are no comments for Debtor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Debtor
        {
            get
            {
                return this._Debtor;
            }
            set
            {
                this._Debtor = value;
                this.OnPropertyChanged("Debtor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Debtor;
        /// <summary>
        /// There are no comments for Creditor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Creditor
        {
            get
            {
                return this._Creditor;
            }
            set
            {
                this._Creditor = value;
                this.OnPropertyChanged("Creditor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Creditor;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sujut.Core.Debtor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Debtors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Debtor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Debtor object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Debtor CreateDebtor(long ID)
        {
            Debtor debtor = new Debtor();
            debtor.Id = ID;
            return debtor;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
        /// <summary>
        /// There are no comments for Expense in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Expense Expense
        {
            get
            {
                return this._Expense;
            }
            set
            {
                this._Expense = value;
                this.OnPropertyChanged("Expense");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Expense _Expense;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sujut.Core.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="allowSearchByName">Initial value of AllowSearchByName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(long ID, bool allowSearchByName)
        {
            User user = new User();
            user.Id = ID;
            user.AllowSearchByName = allowSearchByName;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Firstname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Firstname
        {
            get
            {
                return this._Firstname;
            }
            set
            {
                this.OnFirstnameChanging(value);
                this._Firstname = value;
                this.OnFirstnameChanged();
                this.OnPropertyChanged("Firstname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Firstname;
        partial void OnFirstnameChanging(string value);
        partial void OnFirstnameChanged();
        /// <summary>
        /// There are no comments for Property Lastname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Lastname
        {
            get
            {
                return this._Lastname;
            }
            set
            {
                this.OnLastnameChanging(value);
                this._Lastname = value;
                this.OnLastnameChanged();
                this.OnPropertyChanged("Lastname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Lastname;
        partial void OnLastnameChanging(string value);
        partial void OnLastnameChanged();
        /// <summary>
        /// There are no comments for Property AllowSearchByName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool AllowSearchByName
        {
            get
            {
                return this._AllowSearchByName;
            }
            set
            {
                this.OnAllowSearchByNameChanging(value);
                this._AllowSearchByName = value;
                this.OnAllowSearchByNameChanged();
                this.OnPropertyChanged("AllowSearchByName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _AllowSearchByName;
        partial void OnAllowSearchByNameChanging(bool value);
        partial void OnAllowSearchByNameChanged();
        /// <summary>
        /// There are no comments for Property PaymentInstructions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PaymentInstructions
        {
            get
            {
                return this._PaymentInstructions;
            }
            set
            {
                this.OnPaymentInstructionsChanging(value);
                this._PaymentInstructions = value;
                this.OnPaymentInstructionsChanged();
                this.OnPropertyChanged("PaymentInstructions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PaymentInstructions;
        partial void OnPaymentInstructionsChanging(string value);
        partial void OnPaymentInstructionsChanged();
        /// <summary>
        /// There are no comments for Property TimeZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TimeZone
        {
            get
            {
                return this._TimeZone;
            }
            set
            {
                this.OnTimeZoneChanging(value);
                this._TimeZone = value;
                this.OnTimeZoneChanged();
                this.OnPropertyChanged("TimeZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TimeZone;
        partial void OnTimeZoneChanging(string value);
        partial void OnTimeZoneChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("Language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property Culture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Culture
        {
            get
            {
                return this._Culture;
            }
            set
            {
                this.OnCultureChanging(value);
                this._Culture = value;
                this.OnCultureChanged();
                this.OnPropertyChanged("Culture");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Culture;
        partial void OnCultureChanging(string value);
        partial void OnCultureChanged();
        /// <summary>
        /// There are no comments for Participations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Participant> Participations
        {
            get
            {
                return this._Participations;
            }
            set
            {
                this._Participations = value;
                this.OnPropertyChanged("Participations");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Participant> _Participations = new global::System.Data.Services.Client.DataServiceCollection<Participant>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
// Original file name:
// Generation date: 12/8/2013 6:37:09 PM
namespace Sujut.Models.Api
{
    
    /// <summary>
    /// There are no comments for Sujut.Models.Api.ExpenseApiModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ExpenseApiModel : Sujut.SujutApi.Expense
    {
        /// <summary>
        /// Create a new ExpenseApiModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="amount">Initial value of Amount.</param>
        /// <param name="addedTime">Initial value of AddedTime.</param>
        /// <param name="payerId">Initial value of PayerId.</param>
        /// <param name="debtorIds">Initial value of DebtorIds.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ExpenseApiModel CreateExpenseApiModel(long ID, decimal amount, global::System.DateTime addedTime, long payerId, global::System.Collections.ObjectModel.ObservableCollection<long> debtorIds)
        {
            ExpenseApiModel expenseApiModel = new ExpenseApiModel();
            expenseApiModel.Id = ID;
            expenseApiModel.Amount = amount;
            expenseApiModel.AddedTime = addedTime;
            expenseApiModel.PayerId = payerId;
            if ((debtorIds == null))
            {
                throw new global::System.ArgumentNullException("debtorIds");
            }
            expenseApiModel.DebtorIds = debtorIds;
            return expenseApiModel;
        }
        /// <summary>
        /// There are no comments for Property PayerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long PayerId
        {
            get
            {
                return this._PayerId;
            }
            set
            {
                this.OnPayerIdChanging(value);
                this._PayerId = value;
                this.OnPayerIdChanged();
                this.OnPropertyChanged("PayerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _PayerId;
        partial void OnPayerIdChanging(long value);
        partial void OnPayerIdChanged();
        /// <summary>
        /// There are no comments for Property DebtorIds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<long> DebtorIds
        {
            get
            {
                return this._DebtorIds;
            }
            set
            {
                this.OnDebtorIdsChanging(value);
                this._DebtorIds = value;
                this.OnDebtorIdsChanged();
                this.OnPropertyChanged("DebtorIds");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<long> _DebtorIds = new global::System.Collections.ObjectModel.ObservableCollection<long>();
        partial void OnDebtorIdsChanging(global::System.Collections.ObjectModel.ObservableCollection<long> value);
        partial void OnDebtorIdsChanged();
    }
}
